import type { Metadata } from 'next'
import { MxButton, PlaidButton, UnifiedButton } from './_components'

export const metadata: Metadata = {
  title: 'Create Quiltt App',
  description: 'Generated by Quiltt',
}

export default function Home() {
  return (
    <section className="flex h-full flex-1 items-center justify-center p-4">
      <MxButton />
    </section>
  )
}
