import type { Metadata } from 'next'
import { ConnectorButton } from './_components'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function Home() {
  return (
    <section className="flex h-full flex-1 items-center justify-center p-4">
      <ConnectorButton />
    </section>
  )
}
